/**
 * Payment Milestones  Gated by Quality Checkpoints
 * 
 * Payments are tracked (not processed) through the app.
 * Each milestone unlocks ONLY when the corresponding quality gate passes.
 * 10% retention held until final handover inspection.
 * 
 * Lives in: Roof (financial tracking) + Roof (milestone management)
 */

import { TradeCategory } from './trades';

// ============================================================
// PAYMENT MILESTONE
// ============================================================

export type MilestoneStatus =
    | 'upcoming'          // Not yet due
    | 'due'               // Quality gate passed, payment expected
    | 'overdue'           // Quality gate passed but not paid
    | 'paid'              // Payment received
    | 'blocked'           // Quality gate hasn't passed  can't pay yet
    | 'disputed';         // Client disputes quality

export type MilestoneTrigger =
    | 'contract_signed'       // Deposit
    | 'demolition_complete'   // After demo
    | 'masonry_complete'      // After wet works
    | 'carpentry_installed'   // After carpentry onsite (requires factory QC + delivery inspection)
    | 'painting_complete'     // After painting
    | 'handover_inspection'   // Final walkthrough  workmanship checklist all 
    | 'defect_free_period'    // After 30-day defect liability period
    | 'custom';               // Designer defines custom milestone

export interface PaymentMilestone {
    id: string;
    projectId: string;
    milestoneNumber: number;         // Sequential (1, 2, 3...)

    // What triggers this payment
    name: string;                    // e.g. "Progressive Payment 2  Wet Works"
    description?: string;
    trigger: MilestoneTrigger;
    customTriggerDescription?: string;

    // Amount
    percentage: number;              // % of total contract value
    amount: number;                  // Absolute amount (SGD)
    gst?: number;                    // 9% GST if registered

    // Quality gate
    qualityGateId?: string;          // Links to checkpoint/checklist
    qualityGatePassed: boolean;      // Must be true before payment unlocks
    qualityGateType?: 'workmanship_checklist' | 'factory_qc' | 'delivery_inspection' | 'post_install' | 'handover';

    // Trades involved in this milestone
    tradesIncluded: TradeCategory[];

    // Status
    status: MilestoneStatus;
    dueDate?: string;

    // Payment tracking (not processing  just recording)
    paymentMethod?: 'paynow' | 'bank_transfer' | 'cheque' | 'cash' | 'credit_card';
    paymentReference?: string;       // Transaction reference
    paymentProofUrl?: string;        // Screenshot/receipt upload
    paidAt?: string;
    paidAmount?: number;             // May differ slightly from amount
    confirmedBy?: string;            // Designer confirms receipt

    // Invoice
    invoiceNumber?: string;
    invoiceUrl?: string;             // PDF generated by Roof
    invoiceDate?: string;
}

// ============================================================
// PAYMENT SCHEDULE  Full milestone schedule for a project
// ============================================================

export interface PaymentSchedule {
    projectId: string;
    clientName: string;
    contractValue: number;           // Total contract value
    currency: 'SGD' | 'MYR';

    milestones: PaymentMilestone[];

    // Computed
    totalPaid: number;
    totalRemaining: number;
    paidPercentage: number;
    retentionAmount: number;         // Held until final handover
    retentionPercentage: number;     // Typically 10%

    // Invoice tracking
    totalInvoiced: number;
    totalOutstanding: number;

    lastUpdated: string;
}

// ============================================================
// STANDARD MILESTONE TEMPLATES
// ============================================================

export interface MilestoneTemplate {
    name: string;
    description: string;
    percentage: number;
    trigger: MilestoneTrigger;
    qualityGateType?: PaymentMilestone['qualityGateType'];
    tradesIncluded: TradeCategory[];
}

/** Standard HDB renovation payment schedule */
export const HDB_MILESTONE_TEMPLATE: MilestoneTemplate[] = [
    {
        name: 'Deposit',
        description: 'Upon contract signing and access received',
        percentage: 10,
        trigger: 'contract_signed',
        tradesIncluded: ['preliminaries'],
    },
    {
        name: 'Progressive 1  Demolition & Wet Works',
        description: 'After demolition, masonry, waterproofing, and screed curing complete',
        percentage: 25,
        trigger: 'masonry_complete',
        qualityGateType: 'workmanship_checklist',
        tradesIncluded: ['demolition', 'masonry', 'waterproofing', 'plumbing'],
    },
    {
        name: 'Progressive 2  M&E and Ceiling',
        description: 'After electrical, aircon, and ceiling works',
        percentage: 20,
        trigger: 'custom',
        qualityGateType: 'workmanship_checklist',
        tradesIncluded: ['electrical', 'aircon', 'ceiling'],
    },
    {
        name: 'Progressive 3  Carpentry & Finishes',
        description: 'After carpentry installation (factory QC + delivery inspection passed)',
        percentage: 25,
        trigger: 'carpentry_installed',
        qualityGateType: 'post_install',
        tradesIncluded: ['carpentry', 'flooring', 'glassworks', 'metalworks'],
    },
    {
        name: 'Progressive 4  Painting & Cleanup',
        description: 'After painting and final cleaning',
        percentage: 10,
        trigger: 'painting_complete',
        qualityGateType: 'workmanship_checklist',
        tradesIncluded: ['painting', 'cleaning'],
    },
    {
        name: 'Retention  Handover',
        description: 'Released after final walkthrough. All workmanship checklist items . 30-day defect liability period starts.',
        percentage: 10,
        trigger: 'handover_inspection',
        qualityGateType: 'handover',
        tradesIncluded: [],
    },
];

/** Condo renovation (usually higher value, different structure) */
export const CONDO_MILESTONE_TEMPLATE: MilestoneTemplate[] = [
    {
        name: 'Deposit',
        description: 'Upon contract signing',
        percentage: 10,
        trigger: 'contract_signed',
        tradesIncluded: ['preliminaries'],
    },
    {
        name: 'Progressive 1  Structure & Wet Works',
        description: 'After demolition, masonry, waterproofing complete',
        percentage: 20,
        trigger: 'masonry_complete',
        qualityGateType: 'workmanship_checklist',
        tradesIncluded: ['demolition', 'masonry', 'waterproofing'],
    },
    {
        name: 'Progressive 2  M&E',
        description: 'After M&E rough-in complete',
        percentage: 15,
        trigger: 'custom',
        qualityGateType: 'workmanship_checklist',
        tradesIncluded: ['electrical', 'plumbing', 'aircon'],
    },
    {
        name: 'Progressive 3  Ceiling & Flooring',
        description: 'After ceiling and flooring complete',
        percentage: 15,
        trigger: 'custom',
        qualityGateType: 'workmanship_checklist',
        tradesIncluded: ['ceiling', 'flooring'],
    },
    {
        name: 'Progressive 4  Carpentry',
        description: 'After all carpentry installed and checked',
        percentage: 20,
        trigger: 'carpentry_installed',
        qualityGateType: 'post_install',
        tradesIncluded: ['carpentry', 'glassworks', 'metalworks'],
    },
    {
        name: 'Progressive 5  Painting & Finishing',
        description: 'After painting and final finishes',
        percentage: 10,
        trigger: 'painting_complete',
        qualityGateType: 'workmanship_checklist',
        tradesIncluded: ['painting', 'cleaning'],
    },
    {
        name: 'Retention',
        description: 'Released after handover walkthrough and 30-day defect period',
        percentage: 10,
        trigger: 'handover_inspection',
        qualityGateType: 'handover',
        tradesIncluded: [],
    },
];

// ============================================================
// HELPERS
// ============================================================

/** Generate payment schedule from template */
export function generatePaymentSchedule(
    projectId: string,
    clientName: string,
    contractValue: number,
    currency: PaymentSchedule['currency'],
    template: MilestoneTemplate[],
): PaymentSchedule {
    const milestones: PaymentMilestone[] = template.map((t, i) => ({
        id: `ms_${projectId}_${i + 1}`,
        projectId,
        milestoneNumber: i + 1,
        name: t.name,
        description: t.description,
        trigger: t.trigger,
        percentage: t.percentage,
        amount: Math.round(contractValue * (t.percentage / 100) * 100) / 100,
        qualityGatePassed: false,
        qualityGateType: t.qualityGateType,
        tradesIncluded: t.tradesIncluded,
        status: i === 0 ? 'due' : 'upcoming',
    }));

    const retentionMilestone = milestones.find(m => m.trigger === 'handover_inspection');

    return {
        projectId,
        clientName,
        contractValue,
        currency,
        milestones,
        totalPaid: 0,
        totalRemaining: contractValue,
        paidPercentage: 0,
        retentionAmount: retentionMilestone?.amount || contractValue * 0.10,
        retentionPercentage: retentionMilestone?.percentage || 10,
        totalInvoiced: 0,
        totalOutstanding: 0,
        lastUpdated: new Date().toISOString(),
    };
}

/** Check if a milestone can be unlocked */
export function canUnlockMilestone(milestone: PaymentMilestone): { canUnlock: boolean; reason?: string } {
    if (milestone.status === 'paid') {
        return { canUnlock: false, reason: 'Already paid' };
    }
    if (!milestone.qualityGatePassed && milestone.qualityGateType) {
        return {
            canUnlock: false,
            reason: `Quality gate not passed: ${milestone.qualityGateType.replace(/_/g, ' ')}. Complete the ${milestone.qualityGateType === 'handover' ? 'final walkthrough checklist' : 'workmanship checklist'} first.`,
        };
    }
    return { canUnlock: true };
}

/** Calculate client-facing payment summary */
export function getPaymentSummary(schedule: PaymentSchedule): {
    paid: number;
    remaining: number;
    percentage: number;
    nextMilestone?: { name: string; amount: number; status: string };
    retention: number;
} {
    const paid = schedule.milestones
        .filter(m => m.status === 'paid')
        .reduce((s, m) => s + (m.paidAmount || m.amount), 0);

    const next = schedule.milestones.find(m => m.status === 'due' || m.status === 'upcoming');

    return {
        paid,
        remaining: schedule.contractValue - paid,
        percentage: Math.round((paid / schedule.contractValue) * 100),
        nextMilestone: next ? { name: next.name, amount: next.amount, status: next.status } : undefined,
        retention: schedule.retentionAmount,
    };
}
